apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release-istio-base.yaml
- helm-release-istio-cni.yaml
- helm-release-istiod.yaml
# - helm-release-ztunnel.yaml
- helm-repository.yaml
- namespace.yaml
