apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: atlantis
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      version: "10.1.1"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  values:
    ingress:
      enabled: false
    authenticatedEmailsFile:
      enabled: true
      restricted_access: |-
        s61nov11.shinji.nishioka@gmail.com
    config:
      existingSecret: google-secret
      configFile: |-
        upstreams = [ "http://atlantis.atlantis.svc.cluster.local" ]
        provider = "google"
        skip_auth_routes = "POST=^/events$"
    resources:
      requests:
        cpu: 1m
        memory: 9438k
      limits:
        cpu: 2m
        memory: 13M