apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth2-proxy-route
  namespace: atlantis
spec:
  parentRefs:
  - name: istio-ingress-gateway
    namespace: istio-ingress
  hostnames:
    - atlantis.nishiokatest.xyz
  rules:
  - backendRefs:
    - name: oauth2-proxy
      port: 80
