apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- atlantis/
- cloudflared/
- digger/
- flux-system/
- gateway-infra/
- goldilocks/
- playground/
- zalando/

# 以下未使用
# - harbor/
# - keycloak/