apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:TVq9xvpPhbfepaYT6vVCV4USdwU8GdlGEEpvWf+npLlEKfiEu8kxgxg8u8CoATXlagUR+xfIn+6o1yHMqN9e1FgUYvkFpB+OvX1IRpM5WfcGsVmTpNnkViSJlEuOVCEQXdTqyLD4TMphCvN44zgA4hHfRjDuAoh53e7dNybs2iyk7WeD7cAI+762BhVOxn/4JjacFmDYlqEYZS58W0C7ob6NXC8f9fT8XqxxHf0fU8lV6vDSm8NYlg==,iv:e2PJREyBMwu9j5yO1cAxsnNPBvefmHsX4Lyj4Wp9DoY=,tag:xntyonLryi2vn67Xj/+1uw==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/shinji-nishioka-test/locations/asia-northeast2/keyRings/sops/cryptoKeys/sops-key
      created_at: "2026-01-24T14:41:08Z"
      enc: CiQAwpuH8k+lbcxc+AS7lz96ZJhMIxdMHmho/xSNmvQGdYwgta8SSQC49uDoElzm2UqmFGbPVmJu08xGdncSknN/P+QIhPvcq8+hziyrSGy4zWxn6HLbRfB1OJZucPjlP1reu7k+GG4cRzNPZAOunHo=
  lastmodified: "2026-01-24T14:41:08Z"
  mac: ENC[AES256_GCM,data:f0sQ3lm1K/GUOv9BeJ09qhx4/I1C3gqQkJEZPmA/N+tqgSzCODlPCcXVB1lNgXjh8WVPJNuWsv1eJRHiT/h1fTbjUONLRRzaf8isLHGTPSL3NpHQd7jWh+dimQu2T0hTgYEvDqtfiSkXrWEqz/IDBP537uuGc6G6ywT1RNLW8Hc=,iv:ZzAgUWq09QEQzEVUodrS96fux9e0MHXTbqLSMCAez8U=,tag:Y9pxlq2DX9N9Wm6cH37E4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
