apiVersion: apps/v1
kind: Deployment
metadata:
  name: boba
  namespace: boba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boba
  template:
    metadata:
      labels:
        app: boba
    spec:
      containers:
      - name: boba
        image: boba:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boba
  namespace: boba
spec:
  selector:
    app: boba
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
