apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: digger-route
  namespace: digger
spec:
  parentRefs:
  - name: istio-ingress-gateway
    namespace: istio-ingress
  hostnames:
    - digger.nishiokatest.xyz
  rules:
  - backendRefs:
    - name: digger-digger-backend-web
      port: 3000
